### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by farzadian** [czPechy/instagramProfileCrawler#1]
Hi, 
New instagram limitations made it out of work.
Thanks.

**Comment by czPechy** [comment]
Hi, thanks for information. I will look at it.

**Comment by czPechy** [comment]
@chadmusel Can you please specify problem?
I tried tests for angelinajolieofficial and everithing seems to work.

**Comment by farzadian** [comment]
I have it for crawling 44 post links every min and it was disabled few days ago while instagram made more limitations for scraping. 
I mean maybe your server ip is not banned by instagram yet.

**Comment by czPechy** [comment]
Ouch.. every min? That was kind of expected... Instagram has a lot of mechanisms to block frequent repetitive actions... Not only for crawlers... Same for likes, follows, etc... I use a crawler on 6 production sites. But only once in 15 minutes I download the latest posts and cache it.

**Comment by farzadian** [comment]
Would you please give me ur email and I'll send you the website detail if you can check the code and find the issue please.

**Comment by czPechy** [comment]
@chadmusel it's martin@pecha.pro , but i think its ban per ip address. If I were in your place, I would reduce the number of queries and then write to instagram support "i cant access instagram feed". And he tried to convince them that it was a personal IP. 😄
