### ISSUE TITLE
Cannot Parse JSON

### ISSUE THREAD

**Issue by warifp** [czPechy/instagramProfileCrawler#2]
production.ERROR: Cannot parse JSON from Instagram, please create Issue {"exception":"[object] (czPechy\\instagramProfileCrawler\\ParserException(code: 0): Cannot parse JSON from Instagram, please create Issue at /var/www/XXXXXX/vendor/czpechy/instagramprofilecrawler/src/Parser.php:76)

**Comment by czPechy** [comment]
Its fixed now
